FROM nginx:1.29-alpine
ARG SOURCE_COMMIT=unknown
ARG ARTIFACT_VERSION=1.0.0-SNAPSHOT
LABEL org.opencontainers.image.revision=$SOURCE_COMMIT
LABEL org.opencontainers.image.version=$ARTIFACT_VERSION
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY frontend/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
