#!/usr/bin/env bash
# A staging-only fault injection using disposable local image tags. Published
# Nexus artifacts and application volumes are never changed or removed.
set -Eeuo pipefail
[[ "${DEPLOY_ENV:-staging}" == staging ]] || { echo 'Rollback drills are restricted to staging.' >&2; exit 2; }
state_dir="${DEPLOY_STATE_ROOT:-/var/jenkins_home/deployments/nexora-commerce}/staging"
current_file="${state_dir}/current.env"
[[ -f "$current_file" ]] || { echo 'Deploy a healthy staging release before the drill.' >&2; exit 2; }
baseline_hash="$(sha256sum "$current_file" | cut -d ' ' -f 1)"
# This private state file is generated by deploy.sh. Never enable shell tracing.
set -a
source "$current_file"
set +a
healthy_tag="$IMAGE_TAG"
drill_tag="rollback-drill-${BUILD_NUMBER:-local}"
[[ "$healthy_tag" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$ ]] || exit 2
services=(discovery-service gateway-service user-service product-service media-service order-service)
for service in "${services[@]}"; do
  docker tag "nexora-commerce/${service}:${healthy_tag}" "nexora-commerce/${service}:${drill_tag}"
done
printf 'FROM alpine:3.22\nCMD ["sh", "-c", "exit 1"]\n' |
  docker build -t "nexora-commerce/frontend:${drill_tag}" -
export IMAGE_TAG="$drill_tag"
echo "Injecting an intentionally broken staging frontend: ${drill_tag}"
if DEPLOY_TIMEOUT_SECONDS=30 bash scripts/ci/deploy.sh staging "$drill_tag"; then
  echo 'The fault was unexpectedly accepted; inspect staging immediately.' >&2
  exit 1
fi
echo 'Candidate correctly rejected. Restoring the recorded healthy release.'
DEPLOY_TIMEOUT_SECONDS=360 bash scripts/ci/rollback.sh staging current
[[ "$(sha256sum "$current_file" | cut -d ' ' -f 1)" == "$baseline_hash" ]] || {
  echo 'Healthy release state changed during the drill.' >&2; exit 1;
}
for service in "${services[@]}" frontend; do
  docker image rm "nexora-commerce/${service}:${drill_tag}" >/dev/null
done
echo "PASS: failed candidate rejected; ${healthy_tag} restored and verified; release state preserved."
