server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate /certs/public.crt;
    ssl_certificate_key /certs/private.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /usr/share/nginx/html;
    index index.html;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    location /api/ {
        client_max_body_size 3m;
        proxy_pass https://gateway-service:8080/;
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /trust/ca.pem;
        proxy_ssl_server_name on;
        proxy_ssl_name gateway-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
    location / { try_files $uri $uri/ /index.html; }
}
